src/Entity/Books.php
<?php

namespace App\Entity;


use App\Entity\User;
use App\Entity\Comment;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\BooksRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=BooksRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *  fields={"title"},
 *  message="Une autre livre possède déjà ce titre, merci de le modifier"
 * )
 */
class Books
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5, max=255, minMessage="L\'auteur doit  faire plus de 10 caractères", maxMessage="L\auteur ne peut pas faire plus de 255 caractères")
     */
    private $author;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage="Votre résumé doit  faire plus de 20 caractères")
     */
    private $resume;


    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Image(mimeTypes={"image/png", "image/jpeg", "image/jpg", "image/gif"}, mimeTypesMessage="Vous devez upload un fichier jpg, png ou gif", groups={"create"})
     * @Assert\File(maxSize="2000k", maxSizeMessage="Taille du fichier trop grande", groups={"create"})
     */
    private $coverImage;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=1, max=255, minMessage="Le titre doit  faire plus de 1 caractères", maxMessage="Le titre ne peut pas faire plus de 255 caractères")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="books", orphanRemoval=true)
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="books")
     * @ORM\JoinColumn(nullable=false)
     */
    private $utilisateur;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="book", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\ManyToMany(targetEntity=Genres::class, inversedBy="properties")
     */
    private $genres;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->genres = new ArrayCollection();
    }

    /**
     * Permet d'initialiser le slug automatiquement s'il n'est pas fourni 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void
     */
    public function initializeSlug(){
        if(empty($this->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title." ".$this->id);
        }
    }

     /**
     * Permet de récup le notation moyenne de mon annonce
     */
    public function getAvgRatings()
    {
        // calculer la somme des notations
        // la fonction php array_reduce permet de réduire le tableau à une seule valeur (attention il faut un tableau et pas une array collection d'où l'utilisation de la méthode toArray()) - 2ème paramètre pour la fonction qui va donner chaque valeur à ajouter et le 3ème paramètre c'est la valeur par défaut
        $sum = array_reduce($this->comments->toArray(),function($total,$comment){
            return $total + $comment->getRating();
        },0);

        // faire la division pour avoir la moyenne (ternaire)
        if(count($this->comments) > 0 ) return $moyenne = round($sum / count($this->comments));

        return 0;
    }

    /**
     * Permet de récupérer le commentaire d'un utilisateur par rapport à une fiche livre
     *
     * @param User $utilisateur
     * @return Comment|null
     */
    public function getCommentFromUtilisateur (User $utilisateur)
    {
        foreach($this->comments as $comment){
            if($comment->getUtilisateur() === $utilisateur) return $comment;
        }

        return null;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getResume(): ?string
    {
        return $this->resume;
    }

    public function setResume(string $resume): self
    {
        $this->resume = $resume;

        return $this;
    }



    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCoverImage()
    {
        return $this->coverImage;
    }

    public function setCoverImage($coverImage)
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setBooks($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getBooks() === $this) {
                $image->setBooks(null);
            }
        }

        return $this;
    }

    public function getUtilisateur(): ?User
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?User $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setBook($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getBook() === $this) {
                $comment->setBook(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Genres[]
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genres $genre): self
    {
        if (!$this->genres->contains($genre)) {
            $this->genres[] = $genre;
            $genre->addProperty($this);
        }

        return $this;
    }

    public function removeGenre(Genres $genre): self
    {
        if ($this->genres->removeElement($genre)) {
            $genre->removeProperty($this);
        }

        return $this;
    }

    /**
     * @return Collection|Books[]
     */
    public function getBooks(): Collection
    {
        return $this->books;
    }
    
}

src/Controller/BooksController.php
<?php

namespace App\Controller;

use App\Entity\Books;
use App\Entity\Genres;
use App\Entity\Comment;
use App\Form\AnnonceType;
use App\Form\CommentType;
use App\Entity\UserImgModify;
use App\Form\AnnonceEditType;
use App\Entity\CoverImageModify;
use App\Form\AnnonceCoverImageModifyType;
use App\Repository\BooksRepository;
use App\Service\PaginationService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\Validator\Constraints\All;

class BooksController extends AbstractController
{
    /**
     * @Route("/books/{filtre}/{page<\d+>?1}", name="books_index")
     */
    public function index($page, PaginationService $pagination, $filtre="All"): Response
    {
        $filtres=["All", "Thriller","Fantasy","Fantastique","Policier","Romance","Horreur", "Classique", "Contemporain", "Sciences-fiction"];
        if(in_array($filtre, $filtres)){
            if($filtre == "All"){
                $pagination->setEntityClass(Books::class)
                            ->setPage($page)
                            ->setLimit(10);
            }else{
                $pagination->setEntityClass(Books::class)
                ->setPage($page)
                ->setCategory($filtre)
                ->setLimit(10);

            }
        }else{
            throw $this->createNotFoundException("catégorie inconnue");
        }

        

        return $this->render('books/index.html.twig', [
            'pagination' => $pagination,
            'filtre' => $filtre
        ]);
    }

    /**
     * Permet de créer une fiche de nouveau livre
     * @Route("/books-new", name="books_create")
     * @IsGranted("ROLE_USER")
     * 
     * @return Response
     */
    public function create(EntityManagerInterface $manager, Request $request)
    {
        $books = new Books();
        
        $form = $this->createForm(AnnonceType::class,$books);

        $form->handleRequest($request);
        if($form->isSubmitted()&& $form->isValid()){

            $books->setUtilisateur($this->getUser());

            $file = $form['coverImage']->getData();
            if(!empty($file)){
                $originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$file->guessExtension();
                try{
                    $file->move(
                        $this->getParameter('uploads_directory'),
                        $newFilename
                    );
                }
                catch(FileException $e)
                {
                    return $e->getMessage();
                }
        
                $books->setCoverImage($newFilename);
            }
            $manager->persist($books);
            $manager->flush();

            $this->addFlash(
                'success',
                "la fiche pour <strong>{$books->getTitle()}</strong> a bien été enregistrée"
            );

            return $this->redirectToRoute('books_detail',[
                'slug' =>$books->getSlug()
            ]);
        }
            return $this->render('books/new.html.twig',[
                'myForm' =>$form->createView()
            ]);
            }

    /**
     * Permet de modifier une fiche de livre
     * @Route("books-edit/{slug}", name="books_edit")
     * @Security("(is_granted('ROLE_USER') and user === books.getUtilisateur()) or is_granted('ROLE_ADMIN')", message="Cette annonce ne vous appartient pas, vous ne pouvez pas la modifier")
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @param Books $books
     * @return Response
     */
    public function edit(Request $request, EntityManagerInterface $manager, Books $books)
    {  
       
        $form = $this->createForm(AnnonceEditType::class, $books);
        $form->handleRequest($request);
        
        if($form->isSubmitted() && $form->isValid()){
            $books->setSlug('');

           
            $manager->persist($books);
            $manager->flush();

            $this->addFlash(
                'success',
                "la fiche du livre <strong>{$books->getTitle()}</strong> a bien été modifiée"
            );

            return $this->redirectToRoute('books_detail',[
                'slug' =>$books->getSlug()
            ]);
        }

        return $this->render("books/edit.html.twig",[
            "books" =>$books,
            "myForm" =>$form->createView()
        ]);
    }


    /**
     * Permet de modifier l'image de couverture
     * @Route("/books-edit/{slug}/CoverImageModify", name="books_coverimagemodify")
     * @IsGranted("ROLE_USER")
     * @param Books $books
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @return Response
     */
    public function coverImageModify(Books $books, Request $request, EntityManagerInterface $manager){

        $coverImageModify = new CoverImageModify();
        $form = $this->createForm(AnnonceCoverImageModifyType::class, $coverImageModify);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            if(!empty($books->getCoverImage())){
                unlink($this->getParameter('uploads_directory').'/'.$books->getCoverImage());
            }
        $file = $form['CoverImageModify']->getData();
        if(!empty($file)){
            $originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
            $safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
            $newFilename = $safeFilename.'-'.uniqid().'.'.$file->guessExtension();
            try{
                $file->move(
                    $this->getParameter('uploads_directory'),
                    $newFilename
                );
            }
            catch(FileException $e)
            {
                return $e->getMessage();
            }

            $books->setCoverImage($newFilename);
        }
        $manager->persist($books);
            $manager->flush();

            $this->addFlash(
                'success',
                "la couverture du livre <strong>{$books->getTitle()}</strong> a bien été modifiée"
            );

            return $this->redirectToRoute('books_detail',[
                'slug' =>$books->getSlug('')
            ]);
        }

        return $this->render("books/edit.html.twig",[
            "books" =>$books,
            "myForm" =>$form->createView()
        ]);
    
    }



    /**
     * Permet d'afficher un seul livre
     * @Route("/books-view/{slug}", name="books_detail")
     * 
     * @param [string] $slug
     * @return Response
     */
    public function show(Books $books, Request $request, EntityManagerInterface $manager)
    {
        
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $comment->SetBook($books)
                    ->setUtilisateur($this->getUser());
            $manager->persist($comment);
            $manager->flush();

            $this->addFlash(
                'success',
                'Votre commentaire a bien été pris en compte! '
            );
        }

        

        return $this->render('books/book.html.twig',[
            'books' => $books,
            'myForm' => $form->createView()
        ]);

    }
    
    /**
     * Permet de supprimer une fiche livre
     * @Route("/books-delete/{slug}", name="books_delete")
     * @Security("(is_granted('ROLE_USER') and user === books.getUtilisateur()) or is_granted('ROLE_ADMIN')", message="Vous n'avez pas le droit d'accèder à cette ressource")
     * @param Books $books
     * @param EntityManagerInterface $manager
     * @return Response
     */
    public function delete (Books $books, EntityManagerInterface $manager)
    {
        $this->addFlash(
            'success',
            "La fiche de <strong>{$books->getTitle()}</strong>à bien été supprimée"
        );
        $manager->remove($books);
        $manager->flush();
        return $this->redirectToRoute("books_index");
    }

    


}

templates/books/_book.html.twig
{% set url = path('books_detail', {'slug': books.slug}) %}
            <div class="col-md-4">
                <div class="card bg-light mb-3">
                    <div class="card-header text-center">
                        {{ books.title }} 
                         <br>
                        {% if books.comments | length > 0 %}
                            {% include 'partials/rating.html.twig' with {'rating': books.avgRatings }%} ({{books.comments | length }} avis)
                        {% else %}
                            <small>Pas encore noté</small>
                        {% endif %}
                    </div>
                    <a href="{{url}}">
                        <img src="/uploads/{{books.coverImage}}" alt="image de {{ books.title }}" class="starsimgaff">
                    </a>
                    <div class="card-body">
                        <h4 class="card-title">
                            {{ books.title }}
                        </h4>
                        
                        <a href="{{url}}" class="btn btn-secondary">Lire la fiche du livre</a>
                        {% if (app.user and app.user == books.utilisateur) or is_granted('ROLE_ADMIN') %}
                                <a href="{{ path('books_edit',{'slug': books.slug})}}" class="btn btn-secondary">Modification de l'annonce</a>
                          {% endif %}
                    </div>
                </div>
            </div> 

templates/books/book.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ books.title }}{% endblock %}

{% block body %}

<div class="containerPage">
       <h1>{{books.title}}</h1>
    
       {% if (app.user and app.user == books.utilisateur) or is_granted('ROLE_ADMIN') %}
            <a href="{{ path('books_edit',{'slug': books.slug})}}" class="btn btn-primary mb-2">Modification de l'annonce</a>
           
            <a href="{{ path('books_delete',{'slug': books.slug})}}" class="btn btn-danger" onclick="return confirm('êtes vous sûr de vouloir supprimer l\'annonce: {{books.title}}')">Supprimer</a>
       {% endif %}
</div>
<div class="container_colonne">
<div class="row justify-content-center">
        <div class="col-sm-4">
             <img src="/uploads/{{books.coverImage}}" alt="image de {{ books.title }}" class="starsimg">
 </div>
</div>
    <div class="row justify-content-center" id="">
        <div class="col-sm-8">
 </br>
 </br>
       <p><strong>{{books.author}}</strong></p>
       {% for genre in books.genres %}

       <h4>{{genre.name}}</h4>
        
        {% endfor %}
      <p>pour <strong>{{books.price}}</strong>€ </p>
            </br>
            {{books.resume | raw | nl2br }}
            </br>
              
    </div>
</div>
</div>
    
            
            
<div class="container">
   {# gestion des commentaires #}
            <hr>
    
            {% if books.comments | length > 0 %}
                <h2 class="mb-3">Commentaires de nos lecteurs: </h2>

                <div class="alert alert-info">
                    <h4 class="alert-heading text-center">
                        <div class="row align-items-center">
                            <div class="col">
                                Note globale
                            </div>
                            <div class="col">
                                {% include 'partials/rating.html.twig' with {'rating': books.avgRatings } %}
                                <br><small>(Cette moyenne est calculée sur {{ books.comments | length }} avis)</small>
                            </div>
                        </div>
                    </h4>
                </div>

                {% for comment in books.comments %}
                    <div class="bg-light rounded mb-3 py-3 px-3">
                        <strong>{{ comment.utilisateur.firstName }}</strong> a dit: 
                        <blockquote>
                            {{comment.content | nl2br }}
                        </blockquote>
                        <strong>Note donnée: </strong>
                        {% include 'partials/rating.html.twig' with {'rating': comment.rating} %}

                    </div>
                {% endfor %}
            {% else %}
                <h2>Cette fiche de livre n'a pas encore reçu de commentaire ...</h2>
            {% endif %}
{% if app.user %}
    {% set comment = books.commentFromUtilisateur(app.user) %}
            
             <div class="alert alert-light" id="comment">
                    <h2 class="alert-heading">Votre avis compte!</h2>
                    
                        {% set commment = books.commentFromUtilisateur(app.user) %}
                        {% if comment is not null %}
                            {# déjà commenté , on ne peut pas commenter 2 fois #}
                            <blockquote>
                                {{comment.content}}
                            </blockquote>
                            <strong>Note: </strong>{% include 'partials/rating.html.twig' with {'rating': comment.rating} %}
                        {% else %}
                            {# formulaire pour commenter le livre #}
                                {{ form_start(myForm)}}
                                {{form_widget(myForm)}}
                                <button type="submit" class="btn btn-success">Confirmer</button>
                            {{form_end(myForm)}}

                        {% endif %}
        
{% endif %}
</br>
</div>
</div>
{% endblock %}

templates/books/coverImageModify.html.twig
{% extends 'base.html.twig' %}
{% block title %}Modifier image{% endblock %}

{% block body %}
   <div class="container">
        <h1>Modifier la couverture de {{books.title }}</h1>
        <img src="/uploads/{{ books.coverImage }}" alt="couverture de {{books.title}}">
        {{form_start(myForm)}}
            {{form_widget(myForm)}}
            <button type="submit" class="btn btn-success float-right">Valider la modification</button>
        {{form_end(myForm)}}
    </div>
    {% endblock %}

    
{% block javascripts %}
     <script>
        $('.custom-file input').change(function (e) {
            var files = [];
            for (var i = 0; i < $(this)[0].files.length; i++) {
                files.push($(this)[0].files[i].name);
            }
            $(this).next('.custom-file-label').html(files.join(', '));
        });
    </script>
{% endblock %} 

templates/books/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification du livre {{books.title}}{% endblock %}

{%form_theme myForm _self%}

{% block body %}
    <div class="container">
        
        <h1>Modification du livre  {{books.title}}</h1>

        {{ form_start(myForm) }}

            {{form_widget(myForm)}}
            </br>
            <img src="/uploads/{{ books.coverImage }}" alt="couverture de {{books.title}}" class="img_edit">
             </br>
             </br>
              <a href="{{ path('books_coverimagemodify',{'slug': books.slug}) }}" class="btn btn-secondary">Modifier la couverture</a>
                <button type="submit" class="btn btn-primary">Modification du livre {{books.title}}</button>

        {{ form_end(myForm) }} 
<div class="espace3"></div>
        </br>
            
       


    </div>
{% endblock %} 
{% block _annonce_images_widget %}
    {# Définition du champ annonce_image, la variable form correspond au champ annonce_image #}
    <p>Ici, vous pouvez ajouter vos propres images</p>
    {{ form_widget(form) }}
    <input type="hidden" id="widgets-counter" value="0">
    <div class="form-group">
        <button type="button" id="add-image" class="btn btn-primary">Ajouter une image</button>
    </div>
{% endblock %}

{% block _annonce_images_entry_row %}
    {# entry précise le entry_type de notre AnnonceType au niveau de la collection - donc chaque formulaire ImageType #}
    {# permet de juste afficher le widget donc plus les 0 1 2 3 ... #}
    {{ form_widget(form) }}
{% endblock %}

{% block _annonce_images_entry_widget %}
     {# entry précise le entry_type de notre AnnonceType au niveau de la collection - donc chaque formulaire ImageType #}
     <div class="form-group" id="block_{{id}}">{# id est une variable du block - block_annonce_images_0 #}
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col">
                        {{form_widget(form.url)}}
                        {{form_errors(form.url)}}
                    </div>
                </div>
            </div>
            <div class="col-2">
                <button type="button" class="btn btn-danger" data-action="delete" data-target='#block_{{id}}'>X</button>
            </div>
        </div>

     </div> 
{% endblock %}

{% block javascripts %}
    <script>
   
        $('.custom-file input').change(function (e) {
            var files = [];
            for (var i = 0; i < $(this)[0].files.length; i++) {
                files.push($(this)[0].files[i].name);
            }
            $(this).next('.custom-file-label').html(files.join(', '));
        });
 

        const addImage = document.querySelector("#add-image")
        addImage.addEventListener('click',()=>{
            // compter combien j'ai de form-group pourles indices ex: annonce_image_0_url
            const widgetCounter = document.querySelector("#widgets-counter")
            const index = +widgetCounter.value // le + permet de transformer en nombre pcq .value rend tjrs un string
            console.log(index)
            const annonceImages = document.querySelector("#annonce_images")
            //console.log(annonceImages.dataset.prototype)
            // récupérer le prototype des entrées data-prototype et modifer __name__ par l'index (0,1,2,3)
            const prototype = annonceImages.dataset.prototype.replace(/__name__/g, index) // drapeau/option g pour indiquer qu'on va le faire plusieurs fois
            //console.log(prototype)
            // injecter le code dans la div 
            // https://developer.mozilla.org/fr/docs/Web/API/Element/insertAdjacentHTML
            annonceImages.insertAdjacentHTML('beforeend', prototype)
            widgetCounter.value = index+1
            handleDeleteButtons() // pour mettre à jour le tableau deletes et ajouter l'événement
        })
        const updateCounter = () => {
            const count = document.querySelectorAll('#annonce_images div.form-group').length
            //console.log(count)
            document.querySelector('#widgets-counter').value = count
        }
        const handleDeleteButtons = () => {
            var deletes = document.querySelectorAll("button[data-action='delete']")
            //console.log(deletes)
            deletes.forEach(button => {
                button.addEventListener('click', ()=>{
                    //console.log(button)
                    const target = button.dataset.target // récup le data-target (cible)
                    //console.log(target)
                    const elementTarget = document.querySelector(target)
                    //console.log(elementTarget)
                    // pour éviter bug
                    if(elementTarget){
                        elementTarget.remove() // supprimer l'élément
                    }
                })
            })
        }
        updateCounter()
        handleDeleteButtons()
    </script>
{% endblock %}

templates/books/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos annonces{% endblock %}

{% block body %}
    <div class="container">
    
        <h1 class="my-3">
        Voici nos livres 
            {% if filtre != "All" %}
            {{filtre}}
         {% endif %}
        </h1>
            <div class="row">
               
                    {% for books in bookss %}
                        {% include 'books/_book.html.twig'%}
                     {% endfor %}
        
            </div>
    </div>
{% endblock %}

templates/books/search.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos fiches de livres{% endblock %}

{% block body %}
    <div class="container">
    
        <h1 class="my-3">
        Voici vos recherche pour: {{recherche}}
         
        </h1>
            <div class="row">
               
                    {% for books in bookss %}
                        {% include 'books/_book.html.twig'%}
                     {% endfor %}
        
            </div>
    </div>
{% endblock %}